In [1]:
from datascience import *

In [2]:
Table()  # empty table

In [3]:
Table().with_column('Name', make_array('Lawton', 'Lonzo', 'Bill'))

Name
Lawton
Lonzo
Bill


In [7]:
Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(33, 5, 34)
)

Name,Age
Lawton,33
Lonzo,5
Bill,34


In [8]:
people = Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(33, 5, 34)
)

In [9]:
people

Name,Age
Lawton,33
Lonzo,5
Bill,34


In [11]:
# It's fine to use the plural with_columns and only add a single column
people.with_columns('Employer', make_array("CCC", 'Unemployed', 'CCC'))

Name,Age,Employer
Lawton,33,CCC
Lonzo,5,Unemployed
Bill,34,CCC


In [13]:
people  # didn't change

Name,Age
Lawton,33
Lonzo,5
Bill,34


In [14]:
people.relabeled('Age', 'Trips around the sun')

Name,Trips around the sun
Lawton,33
Lonzo,5
Bill,34


In [15]:
people

Name,Age
Lawton,33
Lonzo,5
Bill,34


---

In [17]:
cones = Table.read_table('data/cones.csv')
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [18]:
cones.num_columns

3

In [19]:
cones.num_rows

7

In [20]:
cones.labels

('Flavor', 'Color', 'Price')

In [21]:
cones.column('Price')

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [22]:
cones.column(2)

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [23]:
cones.column('Price').item(3)

3.5

In [24]:
cones.column('Price').item(0)  # first one is at index 0

3.55

In [25]:
# Crushed ICE: calculate the total price after applying 8.75% sales tax to the Price column

In [29]:
# option 1
tax = cones.column('Price') * (8.75 / 100)
tax + cones.column('Price')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [31]:
# option 2
import numpy as np
np.round(cones.column('Price') * 1.0875, 2)

array([ 3.86,  5.17,  5.71,  3.81,  5.71,  5.71,  5.17])

In [36]:
tax_rate = 0.0875
tax = cones.column('Price') * tax_rate
cones_with_tax = cones.with_column('Price with tax', tax + cones.column('Price'))
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,3.86062
chocolate,light brown,4.75,5.16563
chocolate,dark brown,5.25,5.70937
vanilla,white,3.5,3.80625
strawberry,pink,5.25,5.70937
chocolate,dark brown,5.25,5.70937
bubblegum,pink,4.75,5.16563


In [37]:
cones_with_tax.set_format('Price with tax', CurrencyFormatter)

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [39]:
cones_with_tax.column('Price with tax')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [40]:
Table().with_column('x', make_array(1000, 10000, 9999999999999)).set_format('x', NumberFormatter)

x
"1,000"
"10,000"
"9,999,999,999,999"


In [41]:
Table().with_column('x', make_array(0.5, 0.75, 0.9999)).set_format('x', PercentFormatter)

x
50.00%
75.00%
99.99%


In [42]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [45]:
cones_with_tax.select('Flavor', 'Price with tax')

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [47]:
cones_with_tax.select(0, 3)  # indices work too

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [48]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum


In [49]:
cones.column('Flavor') # only this one makes an array!

array(['strawberry', 'chocolate', 'chocolate', 'vanilla', 'strawberry',
       'chocolate', 'bubblegum'],
      dtype='<U10')

In [51]:
cones_with_tax.drop('Price') # makes a new Table, as usual

Flavor,Color,Price with tax
strawberry,pink,$3.86
chocolate,light brown,$5.17
chocolate,dark brown,$5.71
vanilla,white,$3.81
strawberry,pink,$5.71
chocolate,dark brown,$5.71
bubblegum,pink,$5.17


In [53]:
cones_with_tax.sort('Price with tax')

Flavor,Color,Price,Price with tax
vanilla,white,3.5,$3.81
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
bubblegum,pink,4.75,$5.17
chocolate,dark brown,5.25,$5.71
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [54]:
cones_with_tax.sort('Price with tax', descending=True)

Flavor,Color,Price,Price with tax
chocolate,dark brown,5.25,$5.71
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
chocolate,light brown,4.75,$5.17
bubblegum,pink,4.75,$5.17
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [55]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [56]:
cones_with_tax.take(4)

Flavor,Color,Price,Price with tax
strawberry,pink,5.25,$5.71


In [57]:
cones_with_tax.take(1, 3, 5)

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [61]:
import numpy as np
cones_with_tax.take(np.arange(1, cones_with_tax.num_rows, 2))  # all the odd indices

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [62]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [63]:
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [64]:
cones = cones_with_tax  # remember that you can always overwrite an existing Table!

In [65]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [66]:
cones.where('Flavor', are.equal_to('chocolate'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [68]:
# by default, you get an equality check. This is equivalent to the line above!
cones.where('Flavor', 'chocolate') # this is shorthand for the one above

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [69]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [70]:
cones.where('Price with tax', are.below_or_equal_to(5))

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [71]:
cones.where('Price with tax', are.below_or_equal_to(5)).sort('Price with tax')

Flavor,Color,Price,Price with tax
vanilla,white,3.5,$3.81
strawberry,pink,3.55,$3.86


In [72]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [73]:
cones.where('Color', are.containing('brown'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [74]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [75]:
cones.show(3)  # shows the first 3 rows. .show() with nothing shows everything!

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
